# Generated by Django 4.2.11 on 2024-03-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dumpster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('percents', models.IntegerField()),
            ],
            options={
                'db_table': 'dumpsters',
            },
        ),
    ]
